import requests
print("Strumento di controllo dei server Mojang")
risposta = requests.get("https://status.mojang.com/check")
print("Il server risponde con il codice " + str(risposta.status_code))
print("")
dati = risposta.text
dati = dati.replace("[", "")
dati = dati.replace("]", "")
dati = dati.replace("{", "")
dati = dati.replace("}", "")
dati = dati.replace("\"", "")
dati = dati.replace(":", " -> ")
dati = dati.replace("green", "Attivo")
dati = dati.replace("red", "Non attivo")
dati = dati.replace("orange", "Ha problemi")
dati = dati.replace(",", "\n")
print(dati)
print("")
input("Premi il tasto Invio per uscire")
